### ISSUE TITLE
Should it run on OpenGL 2.0?

### ISSUE THREAD

**Issue by petevine** [pacmancoder/rustzx#22]
I've just tried running `rustzx` on ARM, using soft mesa opengl, but it failed to start:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("0:1(10): error: GLSL 1.40 is not supported. Supported versions are: 1.10, and 1.20\n")', src/libcore/result.rs:785
````

Probably means the default OpenGL 3.3 is required again? I wonder if you could switch to [polydraw](https://github.com/polydraw/polydraw) once it's ready, as it's going to support many different GL/ES backends.

**Comment by pacmancoder** [comment]
Oh, yes, I plan to switch from glium to something more simple. Because OpenGL it is overkill for rendering one sprite :smile:
But I think I can quick fix this today-tomorrow so it will be able to run on OpenGL 2.0, I just must rewrite few strings in shaders.

**Comment by petevine** [comment]
On Mon, 04 Jul 2016 11:49:07 -0700
Vladislav Nikonov <notifications@github.com> wrote:

> Oh, yes, I plan to switch from glium to something more simple. Because OpenGL it is overkill for rendering one sprite :smile:
> But I think I can quick fix this today-tomorrow so it will be able to run on OpenGL 2.0, I just must rewrite few strings in shaders.

Cool, maybe I'll see it running after all :)

**Comment by pacmancoder** [comment]
So, I changed code of shaders to GLSL language level 1.10. Check it out: 1e16afed46aad776355c30ba5c9cf197d68aabd5
But, of course, I can't guarantee that it will work fine on ARM, maybe it will break somewhere in places where endianness is important.

**Comment by petevine** [comment]
I will, thanks!

**Comment by pacmancoder** [comment]
Oh my god, i forgot remove suffix *f* form constant in GLSL. Fixed in: f9a48ca8b6f0dd24ca57ddf57f9724a98be82b16, sorry

**Comment by petevine** [comment]
No problem, I haven't started yet. (fortunately I don't have to recompile the glium crate which takes over 4h currently)

**Comment by petevine** [comment]
No, scratch that! Glium needs recompilation so I'm going to test the changes this last time and get beack to you once the regression gets fixed.

**Comment by petevine** [comment]
Good news! The window comes up - could you recommend a rom for testing? I'm not sure it hangs because I didn't load anything or something's wrong.
 
![rustzx](https://cloud.githubusercontent.com/assets/12054457/16588304/c676ac36-42ce-11e6-80e8-2d998b2c1e86.jpg)

**Comment by pacmancoder** [comment]
Hm... 48k rom is built in binary itself, so emulator core on ARM is not working correctly. Of course you can try to run [this](http://www.retroleum.co.uk/electronics-articles/a-diagnostic-rom-image-for-the-zx-spectrum/) but I'm not sure that this will help.

**Comment by petevine** [comment]
Thanks, I wanted to confirm there was a self test :)

It's probably a graphics issue (X window related?) as the window content stops being updated. What you see in the screenshot is an artifact - on startup, the program displays a row of numbers on the title bar and a completely grey background.

**Comment by petevine** [comment]
Here's what calls are being made before it stops completely. Let me know if you need raw data.

[rustzx_callgrind.txt](https://github.com/pacmancoder/rustzx/files/348030/rustzx_callgrind.txt)

**Comment by pacmancoder** [comment]
Have you tried --nosound option?
I tried to compile it on windows yesterday, by the way, and it shows static gray background also, but it works normal without sound.

**Comment by petevine** [comment]
Bingo! Even though I'd noticed a screenful of audio related errors (I've got pulse running), I concluded it didn't matter, my bad! :)

![rustzx2](https://cloud.githubusercontent.com/assets/12054457/16590314/59b321c0-42d7-11e6-890a-4b5c1ac0c706.jpg)

**Comment by pacmancoder** [comment]
So, great, now we know that portaudio does the thing. Hmm, I think I must to change audio lib :-/ I had too much problems with PortAudio. Can you suggest something ?

**Comment by petevine** [comment]
No idea. However, from the errors it seems it's trying to use ALSA directly instead of pulseaudio and it might be hitting a wrong device (I've got two, USB audio is the right one pulse is using).  Maybe portaudio is OK but needs more configuration.

Here's a screenshot once rustzx freezes:

![audio](https://cloud.githubusercontent.com/assets/12054457/16591164/e368081a-42da-11e6-82fe-f35a8c621962.jpg)

**Comment by petevine** [comment]
The original issue has been fixed 100%, though - shall we close? I've attached the ALSA error messages for completeness above. The problem probably deserves a separate issue.

**Comment by pacmancoder** [comment]
You right, I'll closing it.

**Comment by petevine** [comment]
Thanks!
