### ISSUE TITLE
Panic trying to run external .tzx/.z80

### ISSUE THREAD

**Issue by MagaTailor** [pacmancoder/rustzx#30]
On ARM Linux, I'm unable to run any downloaded roms:

``` shell
$ RUST_BACKTRACE=1 ./rustzx --rom ../../Some_Rom.tzx
```

``` rust
thread 'main' panicked at 'index 42629 out of range for slice of length 16384', src/libcore/slice.rs:549
stack backtrace:
   1: 0xb6f7cc23 - std::sys::backtrace::tracing::imp::write::hf504bc08f2a3011f
   2: 0xb6f80b7b - std::panicking::default_hook::_{{closure}}::h49b28af2d05b6140
   3: 0xb6f7f30b - std::panicking::default_hook::hf5d79ad4f1ead81e
   4: 0xb6f7fa67 - std::panicking::rust_panic_with_hook::h9a3925e37821d434
   5: 0xb6f7f8e3 - std::panicking::begin_panic::h240b4915cec4a07c
   6: 0xb6f7f85f - std::panicking::begin_panic_fmt::hcfb5c8e1936587e5
   7: 0xb6f7f7ef - rust_begin_unwind
   8: 0xb6f8de7b - core::panicking::panic_fmt::h92d7d79877c10aae
   9: 0xb6f8df53 - core::slice::slice_index_len_fail::h0ead1e2e3326bfc4
  10: 0xb6e4ad5f - core::slice::_<impl core..ops..IndexMut<core..ops..Range<usize>> for [T]>::index_mut::h31ebe17e01f75d06
                at /rust/rust-master/src/libcore/slice.rs:683
  11: 0xb6e4a1d7 - core::slice::_<impl core..ops..IndexMut<core..ops..RangeTo<usize>> for [T]>::index_mut::h771fe2e82fcced80
                at /rust/rust-master/src/libcore/slice.rs:705
  12: 0xb6e7171f - rustzx::zx::memory::ZXMemory::load_rom::h9d6c49208f6daf5e
                at /home/odroid/rustzx/src/zx/memory.rs:142
  13: 0xb6e72497 - rustzx::zx::controller::ZXController::load_rom::h46185b805a5fc1f0
                at /home/odroid/rustzx/src/zx/controller.rs:120
  14: 0xb6e7fc2f - rustzx::emulator::Emulator::new::h4ae3c17883f6b238
                at /home/odroid/rustzx/src/emulator/mod.rs:28
  15: 0xb6e7b35f - rustzx::app::rustzx::RustzxApp::from_config::h298f9aba9b39d55e
                at /home/odroid/rustzx/src/app/rustzx.rs:60
  16: 0xb6e826df - rustzx::main::h6b31a6d2189678aa
                at /home/odroid/rustzx/src/main.rs:54
  17: 0xb6f7f717 - std::panicking::try::call::h8e1d2d9d7dca0745
  18: 0xb6f8875f - __rust_try
19: 0xb6f8860f - __rust_maybe_catch_panic
  20: 0xb6f7e8af - std::rt::lang_start::h30b674bef4ff14e2
  21: 0xb6e851a3 - main
  22: 0xb6c0b66f - __libc_start_main
```

Compiled with `rustc 1.12.0-dev (34f35ed29 2016-07-17)`

**Comment by pacmancoder** [comment]
You are using it wrong. ROM is program, which live in spectrum itself, its firmware. Tzx - it is format of tape images. At the moment it is not implemented. But it have pretty big specification and I not planed to implemented it. RustZX can handle **tap** tape images. Find the game in this format (it is very popular) and load it like `rustzx -f --tap your_file.tap`. If it fails to load, try without -f flag - it enables 'fastbtape loading'. And you can use keys F3-F5 to change emulator speed during loading because loading tapes is a very long proccess on ZX Spectrum. Fast loading flag can help fix this in a most cases.

**Comment by petevine** [comment]
Ah, what about `.z80` files?

**Comment by pacmancoder** [comment]
Only tap files supported on 48k and 128k both. (--128k flag). And sna for 48k. But okay, I'll add this in the next release. But not in current month - I very tired of rustzx and want to switch to another project for a while :smile:
Of course, you can add this by yourself and and make Pull request - I'll review it and merge.

**Comment by pacmancoder** [comment]
Oh, and maybe I'll write some gui for emulator in the future and all this things will be less complicated.

**Comment by petevine** [comment]
OK, thanks! I'll test the tap format in a moment :)

**Comment by petevine** [comment]
Works great! The sound is very laggy and completely stops after hitting F5. I think emulation must be too slow.

**Comment by petevine** [comment]
If I switch to a different workspace (X knows nothing has to be drawn) the sound immediately starts playing at normal speed but 100% of a single core starts being used (unlike about 65% previously)

**Comment by pacmancoder** [comment]
Yeah, emulator itself needs medium hardware, so it will maybe slow on ARM. Sound glitches - it is main pain in sound emulation. I have no idea how to avoid them fully, but you can set bigger sound buffer with --latency <Num> flag. Default value is 1024 (something about one FrameEvent time) but you can try to set it to 2048 or 4096 (value must be power of two): `rustzx --latency 4096 ......`. Try this.

**Comment by petevine** [comment]
Nope, latency is completely unrelated. How do you explain the fact `rustzx` doesn't use more than 60% CPU when focused but 100% minimized?

**Comment by petevine** [comment]
That 60% usage corresponds to runbning with `--nosound` by the way.

**Comment by pacmancoder** [comment]
Hmm. Maybe problem is in ayumi lib for ay chip emulation. It is pretty hard for CPU and uses f64 for computations.

**Comment by petevine** [comment]
On Wed, 20 Jul 2016 00:09:16 -0700
Vladislav Nikonov <notifications@github.com> wrote:

> Hmm. Maybe problem is in ayumi lib for ay chip emulation. It is pretty hard for CPU and uses f64 for computations.

I'll get you some profiling data a little later today. It almost looks as if emulation speed is not constant and picks up the moment the graphics part is not being used.

**Comment by petevine** [comment]
Profile data attached in the previous comment.

**Comment by MagaTailor** [comment]
You seem to have lost interest, shall we close this?

**Comment by pacmancoder** [comment]
This was my project for learning Rust and I made many mistakes. I think somewhen I'll have a time to  rewrite it, but for now I am very busy with my work and university :(

**Comment by pacmancoder** [comment]
But let the issue be here. Maybe I'll back to rustzx develop in summer. (But I'll not promise 😄)
I have some ideas about some sort of emulator framework, so maybe I'll rewrite rustzx completely somewhen.

**Comment by MagaTailor** [comment]
This was fun but I prefer to not have any open rust-related issues associated with my account.

Thanks for understanding.
