### ISSUE TITLE
Abnormally high CPU usage

### ISSUE THREAD

**Issue by MagaTailor** [pacmancoder/rustzx#31]
Continuing from https://github.com/pacmancoder/rustzx/issues/30#issuecomment-233913754, I've retested on a 2.2 GHz x86 Athlon machine (about 3x higher single-core performance + Nvidia OpenGL 1.5 + hardware sound mixing) and once a tape is loaded, it starts using 100% CPU right away (focus makes no difference). The sound is choppy too (probably slightly less than on ARM).

Even an empty "Sinclair Research" screen is using 100% cycles. 

**EDIT:**
For reference, `fuse-sdl` (no scaling, SDL 1.x) normally uses 6-12% of the same **ARM** CPU and `pulseaudio` another 3-5%.

**Comment by pacmancoder** [comment]
Hmmmm. Interesting. Tested on i3-3110M 2.4 GHz. 8% cpu, 5-6 % without sound. Weird. Maybe I can improve speed with faster unsafe memory copy functions when loading texture. That's might help, I think. From your profiling info I can conclude some things:
- CPU mod is well-optimized. 
    - but i must optimize registers struct and inline all its methods 
- SDL texture update eats A LOT  of time, i must optimize this.
- I must improve canvas [emulated screen], it uses a lot of time.

Btw, @petevine , how to obtain such profiling info with rust as you get?

**Comment by petevine** [comment]
I originally intended to use `cargo profiler` +  `callgrind` with nicely demangled function names but it was too slow. So I used  `operf` on a release binary compiled with `-g` and annotated with:
`opreport -g --symbols`

**Comment by petevine** [comment]
Edited the original post to include a baseline.

**Comment by MagaTailor** [comment]
Ditto here.
