### ISSUE TITLE
Crash on first key press

### ISSUE THREAD

**Issue by joaolsilva** [pacmancoder/rustzx#32]
Just booting the ZX and pressing enter crashes the emulator.

macOS 10.11.6
rustc 1.18.0

brew info sdl2
sdl2: stable 2.0.5 (bottled), HEAD

```
RUST_BACKTRACE=1 rustzx
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:329
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: sdl2::event::Event::from_ll
  10: sdl2::event::<impl sdl2::sdl::EventPump>::poll_event
  11: <rustzx::app::events::events_sdl::EventsSdl as rustzx::app::events::EventDevice>::pop_event
  12: rustzx::main
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start
```

**Comment by pacmancoder** [comment]
Hello there! I have not tested rustzx on MacOS, I am not sure, but maybe this can be because of using old sdl crate with new sdl library version.

**Comment by joaolsilva** [comment]
The project won't compile when using the latest version of the sdl2 crate (0.30). Using version 0.29 the emulator works and won't crash on key presses, but the key bindings for backspace, enter, etc. aren't working properly.
