### ISSUE TITLE
AY mode is "none" by default, but "mono" is listed as default in --help

### ISSUE THREAD

**Issue by kolen** [pacmancoder/rustzx#37]
`--help` option shows that default value for `--ay` should be `mono`, but in reality it's like `none`: no AY sound.

This is because `ay_enabled` is set to `false` by default

https://github.com/pacmancoder/rustzx/blob/dd40dc4c865987772aa96d96435446c768b6aee3/src/settings.rs#L39

Then, if option is not specified, it stays `false`

https://github.com/pacmancoder/rustzx/blob/dd40dc4c865987772aa96d96435446c768b6aee3/src/settings.rs#L168-L176

**Comment by kolen** [comment]
Turns out it's more complex, it becomes enabled only in 128k mode

https://github.com/pacmancoder/rustzx/blob/dd40dc4c865987772aa96d96435446c768b6aee3/src/settings.rs#L194-L197

So, it works as expected, just `--help` is slightly unclear.

**Comment by pacmancoder** [comment]
fixed in #38
